# Generated by Django 5.0 on 2023-12-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Paper', 'Paper'), ('Leather', 'Leather'), ('Recycled_Meterials', 'Recycled_Meterials')], default='Wood', max_length=100)),
                ('image', models.ImageField(upload_to='Product_images')),
            ],
        ),
    ]
