# Generated by Django 5.0 on 2023-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='Meterial',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Paper', 'Paper'), ('Leather', 'Leather'), ('Cloth', 'Cloth'), ('Recycled Meterials', 'Recycled Meterials'), ('Other', 'Other')], default='Wood', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Jwaleries', 'Jwaleirs'), ('Home Decor', 'Home Decor'), ('Statue', 'Statue'), ('Art Prints', 'Art Prints'), ('Stationary', 'Stationary'), ('Other', 'Other')], default='Wood', max_length=100),
        ),
    ]
