# Generated by Django 5.0 on 2023-12-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0003_alter_product_meterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Meterial',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Paper', 'Paper'), ('Leather', 'Leather'), ('Cloth', 'Cloth'), ('Recycled Meterials', 'Recycled Meterials'), ('Other', 'Other')], default='Wood', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.CharField(choices=[('Jwaleries', 'Jwaleirs'), ('Home Decor', 'Home Decor'), ('Statue', 'Statue'), ('Art Prints', 'Art Prints'), ('Stationary', 'Stationary'), ('Kitchen', 'Kitchen'), ('Other', 'Other')], default='Wood', max_length=100),
        ),
    ]
