# Generated by Django 5.0 on 2024-01-19 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0005_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meterial', models.CharField(choices=[('Wood', 'Wood'), ('Metal', 'Metal'), ('Fabric', 'Fabric'), ('Paper', 'Paper'), ('Leather', 'Leather'), ('Cloth', 'Cloth'), ('Recycled Meterials', 'Recycled Meterials'), ('Other', 'Other')], default='Wood', max_length=100)),
                ('image', models.ImageField(upload_to='Productmetarial_images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productmaterial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meterial', to='artisianshop.productmaterial'),
            preserve_default=False,
        ),
    ]
