# Generated by Django 5.0 on 2024-01-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0007_remove_product_productmaterial_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
