# Generated by Django 5.0 on 2024-01-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
