# Generated by Django 5.0.1 on 2024-01-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0013_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
