# Generated by Django 5.0.1 on 2024-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0015_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Jwaleries', 'Jwaleirs'), ('Home Decor', 'Home Decor'), ('Statue', 'Statue'), ('Art Prints', 'Art Prints'), ('Stationary', 'Stationary'), ('Kitchen', 'Kitchen'), ('Other', 'Other')], max_length=100)),
                ('image', models.ImageField(upload_to='category_image')),
            ],
        ),
    ]
