# Generated by Django 5.0.1 on 2024-02-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0016_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='artisianshop.categorytype'),
        ),
    ]
