# Generated by Django 5.0.1 on 2024-02-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisianshop', '0017_product_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cate',
        ),
        migrations.DeleteModel(
            name='Categorytype',
        ),
    ]
