# Generated by Django 5.0 on 2024-01-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerside', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
