# Generated by Django 5.0 on 2024-01-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerside', '0004_remove_review_review_review_comment_review_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
